name: Docker Build and Deploy

on:
  push:
    branches:
      - master  # Change this to your desired branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this to your desired region

      - name: Build Docker Image
        run: docker build -t my-docker-image .

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 315809974489.dkr.ecr.us-east-1.amazonaws.com

      - name: Tag Docker Image
        run: docker tag my-docker-image:latest 315809974489.dkr.ecr.us-east-1.amazonaws.com/own-repo:latest

      - name: Push Docker Image to ECR
        run: docker push 315809974489.dkr.ecr.us-east-1.amazonaws.com/own-repo:latest

      - name: SSH into EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: 52.91.218.100
          username: ubuntu  # Change this to your EC2 instance username
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Deploy Docker Container
        run: |
          # ssh ubuntu@52.91.218.100 'sudo docker stop my-docker-image || true'
          # ssh ubuntu@52.91.218.100 'sudo docker rm my-docker-image || true'
          ssh ubuntu@52.91.218.100 'sudo docker pull 315809974489.dkr.ecr.us-east-1.amazonaws.com/own-repo:latest'
          ssh ubuntu@52.91.218.100 'sudo docker run -d --name my-docker-image -p 80:3000 315809974489.dkr.ecr.us-east-1.amazonaws.com/own-repo:latest'
